/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2017-09-22 17:40:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <title>Registration</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\r\n");
      out.write("            font-size: 350%;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("            font-variant: normal;\r\n");
      out.write("            font-weight: 200;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-left: 33%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tab{\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding-left: 33%;\r\n");
      out.write("            padding-top: 3%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            padding: 1.6px;\r\n");
      out.write("            font-size: 150%;\r\n");
      out.write("            font-family: Serif;\r\n");
      out.write("            font-weight : 100;\r\n");
      out.write("        }\r\n");
      out.write("        #btn{\r\n");
      out.write("            padding-left: 50%;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#f5f5dc\">\r\n");
      out.write("<header>\r\n");
      out.write("    <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\">COLLEGE</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            <ul class=\"nav navbar-right navbar-nav\">\r\n");
      out.write("\r\n");
      out.write("                <li class=\"active\"><a href=\"index.jsp\"> Home</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("<h1>Registration Page</h1>\r\n");
      out.write("<form method=\"get\" action=\"addStu.jsp\">\r\n");
      out.write("    <div id=\"tab\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td>Student ID</td>\r\n");
      out.write("                <td>:</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"studentid\" required autofocus=\"autofocus\"  ></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr><td>Student Name</td>\r\n");
      out.write("                <td>:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"studentname\" required></td></tr>\r\n");
      out.write("            <tr><td>Group</td><td>:</td><td><input type=\"text\" name=\"group\"  required></td></tr>\r\n");
      out.write("            <tr><td>Subject1</td><td>:</td><td><input type=\"text\" name=\"subject1\" required> </td></tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Subject2</td><td>:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"subject2\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Subject3</td><td>:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"subject3\"  required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("                <td>TOTAL</td><td>:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"total\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Avg</td><td>:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"avg\"></td>\r\n");
      out.write("            </tr> \r\n");
      out.write("       \r\n");
      out.write("            <tr id=\"btn\">\r\n");
      out.write("                <td  colspan=\"2\">\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"index.jsp\" type=\"button\" class=\"btn btn-success\" role=\"button\">Submit</a>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <a href=\"index.jsp\" type=\"button\" class=\"btn btn-warning\" role=\"button\">Reset</a>\r\n");
      out.write("                    \r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar navbar-inverse navbar-fixed-bottom\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <ul class=\"pager\">\r\n");
      out.write("<li class=\"previous\"> <a href=\"admin.jsp\">previous</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
